# Generated by Django 5.1.3 on 2024-12-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zal nomi')),
                ('capacity', models.PositiveIntegerField(verbose_name="Sig'imi")),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzili')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktikligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Zal ',
                'verbose_name_plural': 'Zallar',
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Qator raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktikligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Qator ',
                'verbose_name_plural': 'Qatorlar',
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name="Bo'lim raqami")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktikligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
            ],
            options={
                'verbose_name': "Bo'lim ",
                'verbose_name_plural': "Bo'limlar",
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name="O'rindiq raqami")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktikligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.line', verbose_name='Qatori')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall_app.section', verbose_name="Bo'limi")),
            ],
            options={
                'verbose_name': 'O‘rindiq ',
                'verbose_name_plural': 'O‘rindiqlar',
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sektor nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktikligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.hall', verbose_name='Zal')),
            ],
            options={
                'verbose_name': 'Sektor ',
                'verbose_name_plural': 'Sektorlar',
                'db_table': 'sectors',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.sector', verbose_name='Sektori'),
        ),
        migrations.AddField(
            model_name='line',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.sector', verbose_name='Sektori'),
        ),
    ]
