# Generated by Django 5.1.3 on 2024-12-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0002_alter_hall_managers_alter_line_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_set', to='hall_app.sector', verbose_name='Sektori'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_set', to='hall_app.sector', verbose_name='Sektori'),
        ),
    ]
