# Generated by Django 5.1.3 on 2024-12-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0003_alter_line_sector_alter_section_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_set', to='hall_app.hall', verbose_name='Zal'),
        ),
    ]
