# Generated by Django 5.1.3 on 2024-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0004_alter_sector_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='line_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Qatorlar soni'),
        ),
        migrations.AddField(
            model_name='sector',
            name='section_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Bo'limlar soni"),
        ),
    ]
