# Generated by Django 5.1.3 on 2024-12-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0005_sector_line_count_sector_section_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['number'], 'verbose_name': 'Qator ', 'verbose_name_plural': 'Qatorlar'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['section__number', 'line__number', 'number'], 'verbose_name': 'O‘rindiq ', 'verbose_name_plural': 'O‘rindiqlar'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['number'], 'verbose_name': "Bo'lim ", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelManagers(
            name='hall',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='line',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='seat',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='section',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sector',
            managers=[
            ],
        ),
    ]
