# Generated by Django 5.1.3 on 2024-12-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0006_alter_line_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['line__number', 'section__number', 'number'], 'verbose_name': 'O‘rindiq ', 'verbose_name_plural': 'O‘rindiqlar'},
        ),
    ]
