# Generated by Django 5.1.3 on 2024-12-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0007_alter_seat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['sector__name', 'number'], 'verbose_name': 'Qator ', 'verbose_name_plural': 'Qatorlar'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['line__sector__name', 'line__number', 'section__number', 'number'], 'verbose_name': 'O‘rindiq ', 'verbose_name_plural': 'O‘rindiqlar'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sector__name', 'number'], 'verbose_name': "Bo'lim ", 'verbose_name_plural': "Bo'limlar"},
        ),
    ]
