# Generated by Django 5.1.3 on 2024-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0008_alter_line_options_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='address_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='hall',
            name='address_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Zal nomi'),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Zal nomi'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sektor nomi'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sektor nomi'),
        ),
    ]
