# Generated by Django 5.1.3 on 2024-12-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0009_hall_address_ru_hall_address_uz_hall_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sector__name', 'number'], 'verbose_name': 'Bo‘lim ', 'verbose_name_plural': 'Bo‘limlar'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Sig‘imi'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='line',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(verbose_name='O‘rindiq raqami'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall_app.section', verbose_name='Bo‘limi'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Bo‘lim raqami'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti'),
        ),
    ]
