# Generated by Django 5.1.3 on 2024-12-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tadbir nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tadbir haqida')),
                ('date', models.DateTimeField(verbose_name='Tadbir boshlanish sana va vaqti')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tadbir narxi')),
                ('status', models.CharField(choices=[('no_started', 'Boshlanmagan'), ('started', 'Boshlandi'), ('finished', 'Yakunlangan')], default='no_started', max_length=10, verbose_name='Tadbir holati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktikligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hall_app.hall', verbose_name='Tadbir zali')),
            ],
            options={
                'verbose_name': 'Tadbir ',
                'verbose_name_plural': 'Tadbirlar',
                'db_table': 'events',
            },
        ),
    ]
