# Generated by Django 5.1.3 on 2024-12-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Tadbir ', 'verbose_name_plural': 'Tadbirlar'},
        ),
    ]
