# Generated by Django 5.1.3 on 2024-12-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti'),
        ),
    ]
