# Generated by Django 5.1.3 on 2024-12-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Tadbir ', 'verbose_name_plural': 'Tadbirlar'},
        ),
    ]
