# Generated by Django 5.1.3 on 2024-12-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tadbir haqida'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tadbir haqida'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Tadbir nomi'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Tadbir nomi'),
        ),
    ]
