# Generated by Django 5.1.3 on 2024-12-07 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_event_description_ru_event_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_booking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=900), verbose_name='Chipta bron qilingan vaqti'),
        ),
    ]
