# Generated by Django 5.1.3 on 2024-11-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Ism familiya')),
                ('passport', models.CharField(max_length=255, unique=True, verbose_name='Passport')),
                ('pinfl', models.CharField(max_length=255, unique=True, verbose_name='PINFL')),
                ('course', models.CharField(max_length=255, verbose_name='Kurs')),
                ('edu_lang', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2, verbose_name="Ta'lim tili")),
                ('edu_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_app.edudirection', verbose_name="Ta'lim yo'nalishi")),
                ('edu_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_app.edutype', verbose_name="Ta'lim turi")),
            ],
            options={
                'verbose_name': 'Talaba ',
                'verbose_name_plural': 'Talabalar',
                'db_table': 'students',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['passport'], name='students_passpor_80ed0a_idx')],
            },
        ),
    ]
