# Generated by Django 5.1.3 on 2024-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=1, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Ism familiya'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.CharField(max_length=9, unique=True, verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pinfl',
            field=models.CharField(max_length=14, verbose_name='PINFL'),
        ),
    ]
