# Generated by Django 5.1.3 on 2024-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_student_course_alter_student_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract_amount',
            field=models.FloatField(default=0.0, verbose_name='Shartnoma summasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='student',
            name='debt_amount',
            field=models.FloatField(default=0.0, verbose_name='Qarz summasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_amount',
            field=models.FloatField(default=0.0, verbose_name="To'langan summasi"),
        ),
        migrations.AddField(
            model_name='student',
            name='voucher_amount',
            field=models.FloatField(default=0.0, verbose_name='Voucher summasi'),
        ),
    ]
