# Generated by Django 5.1.3 on 2024-11-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
        ('user_app', '0005_remove_student_debt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='education_app.edudirection', verbose_name="Ta'lim yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='education_app.edutype', verbose_name="Ta'lim turi"),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('chat_lang', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2, verbose_name='Chat tili')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='user_app.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi ',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
    ]
