# Generated by Django 5.1.3 on 2024-11-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_user_phone_alter_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='user_app.student', verbose_name='Talaba'),
        ),
    ]
