# Generated by Django 5.1.3 on 2024-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_lang',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2, null=True, verbose_name='Chat tili'),
        ),
    ]
