# Generated by Django 5.1.3 on 2024-11-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_user_chat_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PHONE_INPUT', 'Telefon raqamini kiritish'), ('PASSPORT_INPUT', 'Pasport maʼlumotlarini kiritish'), ('CONFIRMATION', 'Tasdiqlash kutilmoqda'), ('EDIT', 'Tahrirlash'), ('COMPLETED', 'Tugatildi'), ('BLOCKED', 'Bloklangan')], default='DRAFT', max_length=15, verbose_name='Status'),
        ),
    ]
