# Generated by Django 5.1.3 on 2024-12-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0003_alter_edudirection_options_alter_edutype_options_and_more'),
        ('user_app', '0011_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='education_app.edudirection', verbose_name='Ta’lim yo‘nalishi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2, verbose_name='Ta’lim tili'),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='education_app.edutype', verbose_name='Ta’lim turi'),
        ),
    ]
