# Generated by Django 5.1.3 on 2024-12-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_student_edu_direction_alter_student_edu_lang_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Talaba profil ', 'verbose_name_plural': 'Talaba profillari'},
        ),
    ]
