# Generated by Django 5.1.3 on 2024-12-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_app', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('click', 'Click'), ('payme', 'Payme')], default='cash', max_length=5, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi")),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tranzaksiya ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=10, verbose_name='Holat')),
                ('details', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha tafsilotlar")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_set', to='ticket_app.ticket', verbose_name='Bilet')),
            ],
        ),
    ]
