# Generated by Django 5.1.3 on 2024-12-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov ", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
