# Generated by Django 5.1.3 on 2024-12-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_alter_payment_options_alter_payment_amount_and_more'),
        ('user_app', '0012_alter_student_edu_direction_alter_student_edu_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.user', verbose_name='Foydalanuvchi'),
        ),
    ]
