# Generated by Django 5.1.3 on 2024-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim yo'nalishi")),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name="Ta'lim yo'nalishi")),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name="Ta'lim yo'nalishi")),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishi ",
                'verbose_name_plural': "Ta'lim yo'nalishlari",
                'db_table': 'edu_directions',
            },
        ),
        migrations.CreateModel(
            name='EduType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim turi")),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name="Ta'lim turi")),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name="Ta'lim turi")),
            ],
            options={
                'verbose_name': "Ta'lim turi",
                'verbose_name_plural': "Ta'lim turlari",
                'db_table': 'edu_types',
            },
        ),
    ]
