# Generated by Django 5.1.3 on 2024-12-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edudirection',
            options={'ordering': ['name'], 'verbose_name': "Ta'lim yo'nalishi ", 'verbose_name_plural': "Ta'lim yo'nalishlari"},
        ),
        migrations.AlterModelOptions(
            name='edutype',
            options={'ordering': ['name'], 'verbose_name': "Ta'lim turi", 'verbose_name_plural': "Ta'lim turlari"},
        ),
    ]
