# Generated by Django 5.1.3 on 2024-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0002_alter_edudirection_options_alter_edutype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edudirection',
            options={'ordering': ['name'], 'verbose_name': 'Ta’lim yo‘nalishi ', 'verbose_name_plural': 'Ta’lim yo‘nalishilari'},
        ),
        migrations.AlterModelOptions(
            name='edutype',
            options={'ordering': ['name'], 'verbose_name': 'Ta’lim turi ', 'verbose_name_plural': 'Ta’lim turlari'},
        ),
        migrations.AlterField(
            model_name='edudirection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ta’lim yo‘nalishi'),
        ),
        migrations.AlterField(
            model_name='edudirection',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ta’lim yo‘nalishi'),
        ),
        migrations.AlterField(
            model_name='edudirection',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ta’lim yo‘nalishi'),
        ),
        migrations.AlterField(
            model_name='edutype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ta’lim turi'),
        ),
        migrations.AlterField(
            model_name='edutype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ta’lim turi'),
        ),
        migrations.AlterField(
            model_name='edutype',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ta’lim turi'),
        ),
    ]
