# Generated by Django 5.1.3 on 2024-12-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_app', '0003_alter_event_created_at'),
        ('hall_app', '0007_alter_seat_options'),
        ('user_app', '0011_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tadbir narxi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Bo‘sh o‘rindiqmi?')),
                ('is_paid', models.BooleanField(default=False, verbose_name='To‘landimi?')),
                ('is_booking', models.BooleanField(default=False, verbose_name='Bron qilinganmi?')),
                ('booking_at', models.DateTimeField(blank=True, null=True, verbose_name='Bron qilingan vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event', verbose_name='Tadbir')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.seat', verbose_name='O‘rindiq')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Biletlar',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
