# Generated by Django 5.1.3 on 2024-12-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['event__date', 'seat__line__sector__name', 'seat__line__number', 'seat__section__number', 'seat__number'], 'verbose_name': 'Bilet', 'verbose_name_plural': 'Biletlar'},
        ),
    ]
