# Generated by Django 5.1.3 on 2024-12-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_available',
        ),
    ]
