# Generated by Django 5.1.3 on 2024-12-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_remove_ticket_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-is_booking', '-booking_at', 'event__date', 'seat__line__sector__name', 'seat__line__number', 'seat__section__number', 'seat__number'], 'verbose_name': 'Bilet', 'verbose_name_plural': 'Biletlar'},
        ),
    ]
