# Generated by Django 5.1.3 on 2024-12-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-is_booking', '-booking_at', 'event__date', 'seat__line__sector__name', 'seat__line__number', 'seat__section__number', 'seat__number'], 'verbose_name': 'Chipta ', 'verbose_name_plural': 'Chiptalar'},
        ),
    ]
